# Generated by Django 5.2.7 on 2025-10-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.CharField(max_length=100),
        ),
    ]
